<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64;AnyCPU</Platforms>
    <AssemblyName>FidelSec.Core</AssemblyName>
    <RootNamespace>FidelSec.Core</RootNamespace>
  </PropertyGroup>
</Project>
